#!/bin/sh
#
# Startup script for iNodeAuthService
#
# chkconfig: - 80 01
# description: iNodeAuthService
# processname: iNodeAuthService
# pidfile: /var/run/AuthenMngService.pid
# config: /etc/iNode/iNode.conf

# Get fake config
INODE_CFG="/etc/iNode/inodesys.conf"

#[ -r "$INODE_CFG" ] && . "${INODE_CFG}"
if [ -r "$INODE_CFG" ];then
    LINE=`cat $INODE_CFG`
    INSTALL_DIR=${LINE##*INSTALL_DIR=}
fi

# if INSTALL_DIR is not set, exit
if [ -z "$INSTALL_DIR" ]; then
    echo INSTALL_DIR not set yet
    exit 1
fi

RETVAL=0

# See how we were called.
start() {
    echo -n "Starting AuthenMngService: "
        
    IfExist=`ps awx -o command|awk -F/ '{print $NF}'|grep -x AuthenMngService`
    if [ "$IfExist" != "" ]
    then
        echo "AuthenMngService already running"
    else
        sudo "$INSTALL_DIR/AuthenMngService" &
        echo OK
    fi
    
    IfExist=`ps awx -o command|awk -F/ '{print $NF}'|grep -x iNodeMon`
    if [ "$IfExist" = "" ]
    then
        sleep 5
        sudo "$INSTALL_DIR/iNodeMon" &
    fi
}

stop() {
    echo -n "Stopping AuthenMngService: "
    
    IfExist=`ps awx -o command|awk -F/ '{print $NF}'|grep -x iNodeMon`
    if [ "$IfExist" != "" ]
    then
	sudo "$INSTALL_DIR/iNodeMon" -k
    
    	Sec=0
    	while [ 1 ]
    	do
            IfExist=`ps awx -o command|awk -F/ '{print $NF}'|grep -x iNodeMon`
	    if [ "$IfExist" != "" ]
	    then
		sleep 1
		Sec=`expr $Sec + 1`

		if [ "$Sec" -lt 9 ]
		then
		    sudo killall -9 iNodeMon > /dev/null 2>&1
		else
		    sudo killall -9 iNodeMon
		    break
		fi
	    else
		break
	    fi
    	done
    fi
	
    IfExist=`ps awx -o command|awk -F/ '{print $NF}'|grep -x AuthenMngService`
    if [ "$IfExist" != "" ]
    then
	sudo "$INSTALL_DIR/AuthenMngService" -k
    
    	Sec=0
    	while [ 1 ]
    	do
            IfExist=`ps awx -o command|awk -F/ '{print $NF}'|grep -x AuthenMngService`
	    if [ "$IfExist" != "" ]
	    then
		sleep 1
		Sec=`expr $Sec + 1`

		if [ "$Sec" -lt 9 ]
		then
		    sudo killall -9 AuthenMngService > /dev/null 2>&1
		else
		    sudo killall -9 AuthenMngService
		    break
		fi
	    else
		break
	    fi
    	done
    	
    	echo OK
    else
        echo "AuthenMngService not running"	
    fi
}

# See how we were called.
case "$1" in
  start)
        start
        ;;
  stop)
        stop
        ;;
  restart)
        stop
        sleep 5
        start
        ;;
  *)
        echo "Usage: iNodeAuthService {start|stop|restart}"
        exit 1
esac

exit $RETVAL
